# Generated by Django 3.2.5 on 2021-10-31 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211029_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks_of_user',
            name='taken_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
